// Individual bookable services, transcribed from the "Services" tab of the
// clinic's booking page on that-time.co.uk.
//
// Grouped by the same categories the booking page uses, so the accordion on
// /book-online mirrors what customers see when they get there. Booking itself
// still happens on that-time.co.uk — there is no per-service URL to deep-link
// to, so every "Book" control goes to the same booking page.
//
// IMPORTANT: this is a snapshot, so it will drift as soon as prices change
// there. Nothing keeps the two in step automatically. Treat that-time.co.uk as
// the source of truth and update this file when it changes — or move the list
// into wp-admin so the clinic can maintain it themselves.
//
// Captured 16 September 2026.

export interface Service {
  name: string;
  /** Price in minor units (pence), so it formats through lib/format.ts. */
  price: number;
  /** Human duration, e.g. "1 hr 30 mins". Empty when none was listed. */
  duration: string;
  /** A booking deposit is taken for this service. */
  deposit: boolean;
  /** What's included. Empty for services with no description. */
  summary: string;
}

export interface ServiceCategory {
  name: string;
  services: Service[];
}

/** In the order the booking page lists them. */
export const serviceCategories: ServiceCategory[] = [
  {
    name: 'Liquid lipo & bodysculpting',
    services: [
      {
        name: 'Snatched jaw/chin fat reduction & rf facial',
        price: 6900,
        duration: '1 hr',
        deposit: true,
        summary: 'SIGNATURE SCULPT - SNATCHED JAW / CHIN FAT REDUCTION & RF FACIAL If you’re after a sharper jawline, a more defined chin, and firmer, glowing skin—this treatment was made for you. Signature Sculpt targets stubborn chin fat while tightening and lifting the lower face using advanced, non-invasive technology. It’s all about contour, definition, and co…',
      },
      {
        name: 'Bingo Wings with Liquid Lipo',
        price: 6500,
        duration: '30 mins',
        deposit: true,
        summary: 'Sculpt and tighten your arms with liquid lipo, and cavitation',
      },
      {
        name: 'Mum Tum Makeover with stretch mark reduction',
        price: 19900,
        duration: '1 hr 30 mins',
        deposit: true,
        summary: 'MUMMY MAKEOVER PACKAGE Revitalise your body with our incredible Mummy Makeover Package for only £169 Includes: • Liquid Lipo for Tum, Hips, and Love Handles ~ RF Skin Tightening ~ RF Fractional Microneedling for Stretch Mark Reduction Reclaim your confidence and enjoy a smoother, firmer, and more sculpted body.',
      },
      {
        name: 'Hip Melt with Liquid Lipo',
        price: 6000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Bra Fat Removal',
        price: 6000,
        duration: '1 hr',
        deposit: true,
        summary: '',
      },
      {
        name: 'Ultimate fat blaster - tum/hips/back fat',
        price: 8500,
        duration: '45 mins',
        deposit: true,
        summary: 'This treatment is amazing for removing stubborn fat! Using a combination of liquid lipo fat dissolving gel, sauna blanket plus cavitation, & radio frequency,',
      },
      {
        name: 'Ultimate fat blaster x 3',
        price: 19900,
        duration: '1 hr',
        deposit: true,
        summary: '',
      },
      {
        name: 'Ultimate cellulite/thigh blaster course of 3',
        price: 22000,
        duration: '1 hr 15 mins',
        deposit: true,
        summary: '45 min pressotherapy/lymphatic drainage Liquid lipo thermo wrap Cavitation Rf tightening',
      },
      {
        name: 'Detox & slim with liquid lipo emergency rescue',
        price: 5500,
        duration: '30 mins',
        deposit: true,
        summary: 'This package is ideal for before a night out or to give you a good detox Liquid lipo - tum Infrared sauna blanet Lymphatic drainage',
      },
      {
        name: 'Tummy @ thighs blaster',
        price: 14900,
        duration: '1 hr 30 mins',
        deposit: true,
        summary: 'TUMMY & THIGH BLASTER POWER DUO Only £149 Get ready to sculpt and tone with our Tummy & Thigh Blaster Duo! This powerful package includes everything you need for a total body transformation: Liquid Lipo for legs & tummy 15 mins sauna session to boost fat burn 30 mins pressotherapy for lymphatic drainage and detox Cavitation for tummy…',
      },
      {
        name: 'Ultimate cellulite/thigh blaster',
        price: 9500,
        duration: '1 hr',
        deposit: true,
        summary: '45 min pressotherapy/lymphatic drainage Liquid lipo thermo wrap Cavitation Rf tightening',
      },
      {
        name: 'Sculpt drain and tone',
        price: 9900,
        duration: '1 hr',
        deposit: true,
        summary: 'SCULPT, DRAIN & TONE - BRAND NEW PACKAGE! Get the ultimate body transformation with our exclusive Sculpt, Drain & Tone Package, designed to melt fat, boost circulation, and define your shape! This powerful combo includes: • Liquid Lipo - Dissolves stubborn fat cells • Pressotherapy - Enhances lymphatic drainage & reduces bloating • EMS Sculpt - Tones & stren…',
      },
      {
        name: 'Sculpt drain and tone 2 sessions',
        price: 19800,
        duration: '1 hr',
        deposit: true,
        summary: '',
      },
      {
        name: 'Extreme bum & thighs package',
        price: 14900,
        duration: '1 hr 30 mins',
        deposit: true,
        summary: 'Say hello to our ultimate body contouring combo - designed to lift, sculpt, and define your lower body like never before! This powerful package includes: Thigh sculpting O Liquid lipo © Pressotherapy Cavitation • Bum sculpting " Bum vacuum suction EMS Perfect for targeting stubborn fat, smoothing cellulite, and enhancing curves - all non-surgical and totall…',
      },
      {
        name: 'Derma tone skin tightening with rf - tummy -course of 3',
        price: 19900,
        duration: '30 mins',
        deposit: true,
        summary: 'Radio frequency to tighten the skin with derma tone meseotherapy',
      },
      {
        name: 'Signature sculpt - full body sculpt',
        price: 16900,
        duration: '1 hr 30 mins',
        deposit: true,
        summary: 'A full body contouring treatment combining Liquid Lipo, Cavitation, Wood Therapy, Lymphatic Drainage and an Infrared Sauna Blanket to help break down stubborn fat, reduce bloating and sculpt the body. This treatment supports the lymphatic system, improves circulation and helps contour areas such as the stomach, love handles, thighs, arms and backfat',
      },
      {
        name: 'Course of 6 tummy',
        price: 30000,
        duration: '1 hr',
        deposit: true,
        summary: '',
      },
      {
        name: 'Detox & glo',
        price: 8900,
        duration: '1 hr',
        deposit: true,
        summary: '',
      },
      {
        name: 'Smooth & sculpt cellulite / course of 4',
        price: 24900,
        duration: '1 hr',
        deposit: true,
        summary: 'Helps smooth the appearance of cellulite • Supports body sculpting and contouring Improves skin firmness and texture Supports lymphatic drainage & fluid reduction No downtime',
      },
      {
        name: 'Consultation',
        price: 1000,
        duration: '15 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Summer ready package',
        price: 15000,
        duration: '1 hr 45 mins',
        deposit: true,
        summary: 'THE SUMMER READY LUNA MOON PACKAGE Ready to feel confident, sculpted and summer-ready? Our Summer Ready Luna Moon Package combines some of our most popular treatments to help you look and feel your absolute best. Teeth Whitening Liquid Lipo Fat Dissolve Tummy Sculpt Vacuum Butt Lift Cellulite Reduction All for just £150 Whet…',
      },
    ],
  },
  {
    name: 'Lemon Bottle fat dissolving injections',
    services: [
      {
        name: 'Lemon Bottle 360 snatch',
        price: 28000,
        duration: '1 hr',
        deposit: true,
        summary: 'Lemon bottje mole fat dissolving injections Areas includes Tummy Love handles Back fat Bra fat Cavitation for extra results',
      },
      {
        name: 'Lemon Bottle Chin',
        price: 6000,
        duration: '20 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Lemon Bottle Full Tummy & cavitation',
        price: 12900,
        duration: '35 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Lemon Bottle Hips',
        price: 6500,
        duration: '20 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Lemon Bottle Thighs',
        price: 11000,
        duration: '25 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Lemon Bottle Arms',
        price: 6500,
        duration: '15 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Lemon Bottle Lower Tum',
        price: 7000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Lemon Bottle Bra Fat',
        price: 7000,
        duration: '15 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Lemon bottle full tum & back fat',
        price: 17900,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Special offer lemon arms and tummy and glass facial',
        price: 27900,
        duration: '1 hr',
        deposit: false,
        summary: '',
      },
      {
        name: 'Lemon bottle x 3 chin sessions',
        price: 13000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Lemon bottle chin and tummy',
        price: 18000,
        duration: '30 mins',
        deposit: true,
        summary: 'Lemon bottle tum £120 and chin £60 special offer',
      },
    ],
  },
  {
    name: 'Nurse Tara',
    services: [
      {
        name: 'B12 Injections',
        price: 3000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Forehead Lines (1 Area)',
        price: 10000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Crows Feet (1 Area)',
        price: 10000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Liquid Nose Job',
        price: 17000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Frownlines (2 Areas)',
        price: 14000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'All 3 Areas',
        price: 17000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Lip Filler (0.5ml)',
        price: 9000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Lip Filler (1 ml)',
        price: 14000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Nasolabial Folds',
        price: 20000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Marionette Lines',
        price: 20000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Chemical \'Brow Lift\'',
        price: 8000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Turkey Neck',
        price: 25000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Jawline Defininition & The Wide-Jaw Set',
        price: 15000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Kim K Package',
        price: 50000,
        duration: '1 hr',
        deposit: true,
        summary: '',
      },
      {
        name: 'Lip Flip',
        price: 8000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Aessoa Bright Eyes Package 1',
        price: 9000,
        duration: '1 hr',
        deposit: false,
        summary: '',
      },
      {
        name: 'Aessoa Bright Eyes Package 2',
        price: 15000,
        duration: '1 hr',
        deposit: false,
        summary: '',
      },
      {
        name: 'Russian Lips',
        price: 15000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Hyperhidrosis',
        price: 15000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Bunny Lines',
        price: 3000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Gummy Smiles',
        price: 7000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Smokers Lines',
        price: 8000,
        duration: '30 mins',
        deposit: false,
        summary: '',
      },
      {
        name: 'Down Turned Mouths',
        price: 17500,
        duration: '30 mins',
        deposit: false,
        summary: '',
      },
      {
        name: 'Dimpled / \'Pebbled\' Chins',
        price: 10000,
        duration: '30 mins',
        deposit: false,
        summary: '',
      },
      {
        name: 'Deep Line Rejuvenation',
        price: 20000,
        duration: '30 mins',
        deposit: false,
        summary: '',
      },
      {
        name: 'Cheek Augmentation 1',
        price: 15000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Cheek Augmentation 2',
        price: 27500,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Hand Filler Rejuvenation',
        price: 25000,
        duration: '30 mins',
        deposit: false,
        summary: '',
      },
      {
        name: 'Tear Trough Filler',
        price: 14000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Kim Ken Package 1',
        price: 40000,
        duration: '1 hr',
        deposit: true,
        summary: '',
      },
      {
        name: 'Kim Ken Package 2',
        price: 60000,
        duration: '1 hr',
        deposit: true,
        summary: '',
      },
      {
        name: 'Jaw Sculpting 1',
        price: 20000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Jaw Sculpting 2',
        price: 30000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Lip Reconstruction 1',
        price: 20000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Lip Reconstruction 2',
        price: 25000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Dissolving',
        price: 15000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Hayfever Injections',
        price: 5000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
    ],
  },
  {
    name: 'Cosmetic laser Teeth Whitening',
    services: [
      {
        name: 'Cosmetic laser Teeth Whitening',
        price: 6500,
        duration: '45 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Cosmetic Teeth Whitening (Ultra)',
        price: 7500,
        duration: '1 hr',
        deposit: true,
        summary: '',
      },
      {
        name: 'Cosmetic Teeth Whitening for 2',
        price: 12000,
        duration: '45 mins',
        deposit: true,
        summary: '',
      },
    ],
  },
  {
    name: 'RF Fractional Micro Needling',
    services: [
      {
        name: 'Rf Fractional Micro Needling/morpheus 8 face',
        price: 8500,
        duration: '45 mins',
        deposit: true,
        summary: '“Fractional microneedling uses ultra-fine needles combined with radiofrequency energy to create controlled micro-channels in the skin. This triggers your body’s natural healing response, stimulating collagen and elastin from deep within, not just the surface.” “Because it’s fractional, only a portion of the skin is treated at one time. That means powerful…',
      },
      {
        name: 'Fractional Micro Needling - Face & Neck with polyneuclide (salmon dna)',
        price: 9500,
        duration: '45 mins',
        deposit: false,
        summary: '',
      },
      {
        name: 'Fractional Micro Needling - Stomach',
        price: 8500,
        duration: '30 mins',
        deposit: false,
        summary: '',
      },
      {
        name: 'Fractional Micro Needling - Neck',
        price: 5000,
        duration: '20 mins',
        deposit: false,
        summary: '',
      },
      {
        name: 'Stretch Mark Reduction',
        price: 8500,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Stretch Mark Reduction - Course of 3',
        price: 21000,
        duration: '1 hr',
        deposit: true,
        summary: '',
      },
    ],
  },
  {
    name: 'Facial Treatments',
    services: [
      {
        name: 'Microdermabrasion with led and enzyme peel',
        price: 6000,
        duration: '40 mins',
        deposit: true,
        summary: 'Reveal brighter, smoother skin with this deep exfoliation treatment using fine crystals to reduce uneven texture, fine lines, and pigmentation. Now includes light therapy for additional healing and Rejuvenating benefits',
      },
      {
        name: 'Microneedling',
        price: 7000,
        duration: '45 mins',
        deposit: true,
        summary: 'Microneedling is the ultimate collagen booster, helps with anti-aging, reducing pigmentation, brighteing the skin, helps with stubborn scarring and much more with the most exclusive skin boosters used alongside the treatment to help your skin concerns.',
      },
      {
        name: 'Eye Bag Reduction - blephorant',
        price: 6000,
        duration: '45 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Deluxe Facial',
        price: 6000,
        duration: '1 hr',
        deposit: true,
        summary: 'Deluxe Facial Double cleanse ~ Steam ~ Exfoliate Hot towels Blackhead extraction Face & shoulder massage ~ Gentle enzyme peel V Cooling mask vice globing ~ Serum \\ SPF',
      },
      {
        name: 'Clinicare Cinderella Facial',
        price: 5000,
        duration: '45 mins',
        deposit: false,
        summary: '',
      },
      {
        name: 'Crystal Carboxy Facial',
        price: 5500,
        duration: '40 mins',
        deposit: true,
        summary: '“A Carboxy Facial is a non-invasive treatment that uses carbon dioxide to increase oxygen delivery to the skin. When CO₂ is applied, the skin responds by sending oxygen-rich blood to the area, instantly boosting circulation and skin vitality.” “This results in brighter, firmer, more hydrated skin with a healthy glow.” •	Dull, tired or stressed skin •	D…',
      },
      {
        name: 'Collagen Lift ultimate Face & Neck with led light',
        price: 8500,
        duration: '45 mins',
        deposit: true,
        summary: 'Non surgical facelift using high grade radio frequency plumps tightenes and rejuvenating. Microdermabrasion is done before',
      },
      {
        name: 'Glass facial',
        price: 6500,
        duration: '50 mins',
        deposit: true,
        summary: 'Combining the dermaplaning + Microdermabrasion to give the ultimate glass skin finish. Perfect for all skin types before that big event, holiday or generally to maintain your skin. Double cleanse - enzyme peel - Dermaplaning - Microdermabrasion - gold hydrauloronic mask- Ice globes - Hydrating Serum - Moisturiser - spf',
      },
      {
        name: 'Hydra facial',
        price: 7000,
        duration: '45 mins',
        deposit: true,
        summary: 'Targeted for your skin concerns, deep hydration, cleanse, exfoliation, great to reduce pigmentation, anti aging and bring life to your skin again! Includes personliased skin boosters for that added glow & brightness to your skin. Double cleanse -Enzyme peel, Microdermabrasion - HydraFacial - Skin Booster - Hydrating serum - Face mask - Ice globe massage…',
      },
      {
        name: 'Express facial',
        price: 3500,
        duration: '30 mins',
        deposit: true,
        summary: 'Restore your skins glow with our gorgeous and uplifting express facial. If you\'re new to facials or just want a little skin pick-me-up, this one\'s for you! What does it include? Wewill examine your skin and work out what\'s best for you, also give lots of product recommendations. Expect a skin detox as we thoroughly cleanse & exfoliate, tone, and moisturise…',
      },
      {
        name: 'Pink glow',
        price: 8500,
        duration: '45 mins',
        deposit: true,
        summary: 'PINK GLOW is an advanced whitening cocktail indicated to lighten hyperpigmented areas of the skin and prevent formation of new imperfections on the face and body. The combination of active ingredients in Mesoheal PINK GLOW acts on the process of melanin production in order to achieve a depigmenting, lightening',
      },
      {
        name: 'Collagen Neck lift with led light',
        price: 4000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Microneedling & Advanced skin booster',
        price: 9500,
        duration: '45 mins',
        deposit: false,
        summary: 'Microneedling is the ultimate collagen booster, helps with anti-aging, reducing pigmentation, brighteing the skin, helps with stubborn scarring and much more with the most exclusive skin boosters used alongside the treatment to help your skin concerns. We have a range of skin boosters to help target your specific concerns such as brightening, lightening, a…',
      },
      {
        name: 'Microneedling and exsommes',
        price: 9500,
        duration: '45 mins',
        deposit: true,
        summary: 'Microneedling is the ultimate collagen booster, helps with anti-aging, reducing pigmentation, brighteing the skin, helps with stubborn scarring and much more with the most exclusive skin boosters used alongside the treatment to help your skin concerns. Exosomes have distinctive capabilities, including facilitating intercellular communication, delivering bio…',
      },
      {
        name: 'Biorepeel course of 3',
        price: 16000,
        duration: '30 mins',
        deposit: false,
        summary: '',
      },
      {
        name: 'Collagen lift ultimate course of 3',
        price: 19900,
        duration: '45 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Hydrafacial & microneedling',
        price: 9500,
        duration: '45 mins',
        deposit: true,
        summary: 'This popular package, the ultimate glow, offers a rejuvenating experience by combining the benefits of microneedling with the hydration & moisture given from the hydrafacial. Perfect before special occasions such as birthdays, weddings,',
      },
      {
        name: 'Cocoon facial',
        price: 6000,
        duration: '1 hr',
        deposit: true,
        summary: 'Your experience includes: • A gentle cleanse and soft exfoliation • Slow, restorative massage of the face, scalp, neck and shoulders • LED light therapy to support skin health and natural glow • A warm massage blanket to help the body fully relax • A nourishing mask chosen for your skin on the day • Quiet, unhurried time to completely switch off',
      },
    ],
  },
  {
    name: 'Laser Clinic',
    services: [
      {
        name: 'IPL Full Body Laser - Bring a Bestie - 6 session\'s',
        price: 99900,
        duration: '1 hr',
        deposit: true,
        summary: '',
      },
      {
        name: 'IFull Body Laser 6 sessions',
        price: 109900,
        duration: '1 hr',
        deposit: true,
        summary: '',
      },
      {
        name: 'Bikini package 6 sessions',
        price: 55000,
        duration: '45 mins',
        deposit: true,
        summary: 'Bikini Underarms Half legs 6 sessions',
      },
      {
        name: 'Underarms',
        price: 4000,
        duration: '20 mins',
        deposit: true,
        summary: 'Laser underarms one session',
      },
      {
        name: 'Underarms - 6 sessions',
        price: 18000,
        duration: '25 mins',
        deposit: true,
        summary: 'Underarms- 6 session',
      },
      {
        name: 'Face & arms 6 sessions',
        price: 39900,
        duration: '30 mins',
        deposit: false,
        summary: '6 sessions full face 6 sessions full arms',
      },
      {
        name: 'Lower legs',
        price: 6000,
        duration: '20 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Bikini & underarms 8 sessions',
        price: 25000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Full body laser 6 sessions',
        price: 40000,
        duration: '40 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Laser face 8 sessions special offer',
        price: 22000,
        duration: '30 mins',
        deposit: false,
        summary: '',
      },
    ],
  },
  {
    name: 'Chemical Peels',
    services: [
      {
        name: 'Bio RePeel',
        price: 7000,
        duration: '30 mins',
        deposit: true,
        summary: 'BioRePeelCI3 is used to improve the appearance of the skin. It is a non-invasive procedure that can be used to treat a variety of skin concerns, including:* Fine lines and wrinkles, Hyperpigmentation, sun damage, loss of elasticity, dullness. BioRePeelCI3 works by stimulating the production of new collagen and elastin, which helps to plump up the skin',
      },
      {
        name: 'Biorepeel',
        price: 10000,
        duration: '35 mins',
        deposit: true,
        summary: 'BioRePeelCI3 is used to improve the appearance of the skin. It is a non-invasive procedure that can be used to treat a variety of skin concerns, including:* Fine lines and wrinkles, Hyperpigmentation, sun damage, loss of elasticity, dullness. BioRePeelCI3 works by stimulating the production of new collagen and elastin, which helps to plump up the skin',
      },
    ],
  },
  {
    name: 'Spray Tanning',
    services: [
      {
        name: 'Liquid Lipo Spray Tanning',
        price: 3000,
        duration: '30 mins',
        deposit: false,
        summary: '',
      },
    ],
  },
  {
    name: 'Vacuum Therapy non surgical bum lift',
    services: [
      {
        name: 'Extreme bbl non surgical',
        price: 7900,
        duration: '1 hr',
        deposit: true,
        summary: 'This amazing treatment gives rounder, peachier, fuller lifted peachy bum No needles, n filler and no downtime! includes Rf tightening, cavitation and vacuum therapy.',
      },
      {
        name: 'Extreme bbl x 3',
        price: 19900,
        duration: '1 hr',
        deposit: true,
        summary: 'Course of 3 This amazing treatment gives rounder, peachier, fuller lifted peachy bum No needles, n filler and no downtime! includes Rf tightening, cavitation and vacuum therapy.',
      },
    ],
  },
  {
    name: 'Skin boosters',
    services: [
      {
        name: 'Seventy Hyal',
        price: 9000,
        duration: '15 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Course of 3 Seventy Hyal',
        price: 22000,
        duration: '15 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Lumi Eyes',
        price: 9000,
        duration: '15 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Lumi Eyes pro Course of 3',
        price: 24000,
        duration: '15 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Pure eyes course of 3',
        price: 24000,
        duration: '20 mins',
        deposit: true,
        summary: 'Course of 3',
      },
      {
        name: 'Lumi pro',
        price: 9500,
        duration: '30 mins',
        deposit: true,
        summary: 'Lumipro. This new skin booster contains 33% HIGHER hyaluronic acid concentration than the industry\'s leading brands! In others words... it\'s the best of the best for RESULTS But is this treatment suitable for you? Benefits • Intense Hydration deep within the Skin • Treats Lines & Wrinkles • Plumps & Regenerate Skin Volume • Smooths skin texture & improves du…',
      },
      {
        name: 'Lemon bottle skin booster',
        price: 8000,
        duration: '40 mins',
        deposit: true,
        summary: '11 high-content amino acids, multivitamins, multi-peptides, and antioxidants required for skin cells with HA to provide them directly to the skin, engaging in the new production of collagen and elastin and supplying nutrients needed for the skin.',
      },
      {
        name: 'Pure eyes',
        price: 8500,
        duration: '20 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Lumi lips',
        price: 9500,
        duration: '20 mins',
        deposit: true,
        summary: 'Skin booster for lips',
      },
      {
        name: 'Profhilo face',
        price: 16000,
        duration: '20 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Meseotherapy with medical grade serum',
        price: 8500,
        duration: '25 mins',
        deposit: true,
        summary: '',
      },
    ],
  },
  {
    name: 'Collagen lift - rf skin tightening medical grade',
    services: [
      {
        name: 'Collagen Lift - Face - non surgical facelift',
        price: 6500,
        duration: '40 mins',
        deposit: true,
        summary: 'Tighten and firm your skin with this non-invasive radiofrequency treatment that stimulates collagen production. Now enhanced with light therapy to boost results, it\'s perfect for reducing fine lines, sagging, and lack of elasticity.',
      },
      {
        name: 'Collagen Lift - Arms',
        price: 6500,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Collagen Lift - Tummy',
        price: 6500,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Collagen Lift - Thighs',
        price: 6500,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Collagen lift course of 4 arms',
        price: 19900,
        duration: '30 mins',
        deposit: true,
        summary: 'Course of 6 collagen lift',
      },
      {
        name: '4 x tummy collagen lift 4 x bun collagen lift',
        price: 30000,
        duration: '45 mins',
        deposit: true,
        summary: 'Special offer £300',
      },
    ],
  },
  {
    name: 'Pressotherapy',
    services: [
      {
        name: 'Full Body Bikini Blitz with liquid lipo',
        price: 9900,
        duration: '1 hr',
        deposit: true,
        summary: 'Full body liquid lipo wrap 45 mins pressotherapy',
      },
      {
        name: 'Pressotherapy',
        price: 4000,
        duration: '45 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Pressotherapy and liquid lipo tum',
        price: 6000,
        duration: '1 hr',
        deposit: true,
        summary: 'Liquid lipo tummy hips backk fat Presseotherapy Cavitation',
      },
    ],
  },
  {
    name: 'Polynucleotide',
    services: [
      {
        name: 'Vitaron lower face (or neck)',
        price: 13000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Polynucleotide eyes',
        price: 9500,
        duration: '20 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Vitaron face and eyes',
        price: 18500,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Neck',
        price: 13000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Vitaron eyes',
        price: 13000,
        duration: '15 mins',
        deposit: true,
        summary: '',
      },
    ],
  },
  {
    name: 'Home kits liquid lipo',
    services: [
      {
        name: '5 day liquid lipo home kit',
        price: 6000,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Skinny package 4 weeks',
        price: 7900,
        duration: '15 mins',
        deposit: true,
        summary: '4 weeks',
      },
    ],
  },
  {
    name: 'Hair loss',
    services: [
      {
        name: 'Hair loss exsommes course of 6',
        price: 24000,
        duration: '45 mins',
        deposit: true,
        summary: 'Course of 6',
      },
    ],
  },
  {
    name: 'Intimate whitening Course of 4',
    services: [
      {
        name: 'Intimate whitening course of 4',
        price: 24000,
        duration: '30 mins',
        deposit: true,
        summary: '“Intimate whitening is a non-invasive treatment designed to gently brighten and even the skin tone in intimate areas where pigmentation can naturally occur over time.” “Darkening in these areas is very common and can be caused by hormones, shaving, friction, ageing, or pregnancy. The treatment works by exfoliating the surface skin and supporting cell rene…',
      },
    ],
  },
  {
    name: 'Ems',
    services: [
      {
        name: 'Ems sculpting 2 areas - course of 6',
        price: 28000,
        duration: '30 mins',
        deposit: true,
        summary: '2 areas course of 6',
      },
      {
        name: 'Ems sculpt 6 sessions offer £199 one area',
        price: 19900,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Ems sculpt 1 session',
        price: 3500,
        duration: '30 mins',
        deposit: true,
        summary: '',
      },
      {
        name: 'Body contour course',
        price: 124900,
        duration: '6 hr',
        deposit: false,
        summary: '',
      },
    ],
  },
  {
    name: 'Special offers',
    services: [
      {
        name: 'Bring a bestie and transform together',
        price: 19900,
        duration: '1 hr 45 mins',
        deposit: true,
        summary: 'BRING A FRIEND & TRANSFORM TOGETHER Because confidence is even better when it’s shared! For a limited time, you and your friend can each enjoy a complete body contouring and skin rejuvenation experience. Each person receives: 30 Minute EMS Session Liquid Lipo Body Contouring (No Needles) Pressotherapy Lymphatic Drainage Collage…',
      },
      {
        name: 'Mia collagen arms thighs ultra teethwhitening',
        price: 16500,
        duration: '40 mins',
        deposit: false,
        summary: '',
      },
    ],
  },
];

export const serviceCount = serviceCategories.reduce((n, c) => n + c.services.length, 0);
